name: actions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  qemu-user-static:
    runs-on: ubuntu-latest
    env:
      VERSION: 8.2.5-2
      ORIGIN_VERSION: 8.2.5+ds-2

    steps:
      - name: Download x86_64
        run: |
          mkdir -p packages/x86_64 releases
          wget "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_${{ env.ORIGIN_VERSION }}_amd64.deb"
          dpkg-deb -R qemu-user-static_*_amd64.deb packages/x86_64
          find packages/x86_64/usr/bin -type l -delete
          for i in packages/x86_64/usr/bin/qemu-*-static; do mv "$i" "releases/x86_64-$(basename "$i")"; done

      - name: Download arm64
        run: |
          mkdir -p packages/aarch64 releases
          wget "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_${{ env.ORIGIN_VERSION }}_arm64.deb"
          dpkg-deb -R qemu-user-static_*_arm64.deb packages/aarch64
          find packages/aarch64/usr/bin -type l -delete
          for i in packages/aarch64/usr/bin/qemu-*-static; do mv "$i" "releases/aarch64-$(basename "$i")"; done

      - name: Generate checksum
        run: sha256sum releases/* > CHECKSUMS
        working-directory: packages

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          artifacts: "releases/*"
          token: ${{ secrets.GITHUB_TOKEN }}
